This file documents my prep for the End Semester Examination for my LAB

In [1]:
"""Write a Python function that generates a list of numbers from 1 to n and prints:
All odd numbers
All even numbers (as choice based)"""
def sequence(n,choice):
    nums=list(range(1,n+1))
    if(choice.lower()=="odd"):
        print("Odd numbers: ")
        for num in nums:
            if num%2!=0:
                print(num,end=" ")
    else:
        print("Even Numbers: ")
        for num in nums:
            if(num%2==0):
                print(num,end=" ")

sequence(10,"odd")

Odd numbers: 
1 3 5 7 9 

In [2]:
""" Write a Python function that takes an integer and returns the sum of its digits"""
def digsum(num):
    sum=0
    while(num!=0):
        sum=sum+num%10
        num//=10
    print(sum)

digsum(123)

6


In [3]:
""" Write a Python function that takes an integer and returns the reverse of the number."""
def reverse(num):
    rev=0
    while(num!=0):
        rev=rev*10+num%10
        num//=10
    print(rev)
reverse(123)

321


In [4]:
""" Write a Python function that takes two inputs and prints:
Whether both inputs are of the same data type
Whether their values are equal"""
def checktype(a,b):
    if type(a) == type(b):
        print("Both inputs are of the same data type")
    else:
        print("Inputs are of different data types")

    if a == b:
        print("Both inputs have equal values")
    else:
        print("Inputs have different values")
checktype(56,"56")

Inputs are of different data types
Inputs have different values


In [5]:
"""Write a Python function that takes a string and returns:
Number of alphabets
Number of digits
Number of special characters"""
def numchar(str):
    alpha=0
    dig=0
    spc=0
    for ch in str:
        if ch.isalpha():
            alpha+=1
        elif ch.isdigit():
            dig+=1
        else:
            spc+=1
        
    return alpha,dig,spc
numchar("Hi23f&$gd6")

(5, 3, 2)

In [6]:
import numpy as np
arr=np.array([1,23,45])
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
"""Generate a 3x4 NumPy array with random integers between 1 
and 50. 
a. Calculate and print the Mean, Median, and Standard Deviation 
of the array 
b. Print the Sum of all elements and the sum of each row. 
c. Reshape the 3x4 array into a 2x6 array and print it. """

arr=np.random.randint(1,51,size=(3,4))
print(arr)
print("Mean: ",arr.mean())
print("Median: ",np.median(arr))
print("Standard Deviation: ",arr.std())
print("Summ of all elements: ",np.sum(arr))
print("Sum of each row: ",np.sum(arr,axis=1))
arr=arr.reshape(2,6)
print(arr)

[[ 8 25  2 22]
 [26 10 10  7]
 [36  1 47 37]]
Mean:  19.25
Median:  16.0
Standard Deviation:  14.520818388323251
Summ of all elements:  231
Sum of each row:  [ 57  53 121]
[[ 8 25  2 22 26 10]
 [10  7 36  1 47 37]]


In [8]:
"""Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following 
linear algebra operations 
a. Matrix addition 
b. Matrix subtraction 
c. Matrix multiplication (element-wise and dot product) 
d. Transpose of a matrix 
e. Determinant and inverse (if applicable) """

import numpy as np

# Define matrices directly
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Matrix A:")
print(arr1)

print("\nMatrix B:")
print(arr2)

print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nElement-wise Multiplication:")
print(arr1 * arr2)

print("\nDot Product:")
print(arr1 @ arr2)

print("\nTranspose of A:")
print(arr1.T)

print("\nDeterminant of A:", np.linalg.det(arr1))

if abs(np.linalg.det(arr1)) > 1e-6:
    print("\nInverse of A:")
    print(np.linalg.inv(arr1))
else:
    print("\nMatrix A not invertible")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A: 0.0

Matrix A not invertible


In [9]:
""" Write a Python program to find and print all 
the values that occur exactly once in a given 2D matrix"""
A=[[1,2,3],
   [3,4,5],
   [5,6,7]]
freq={}
for row in A:
    for val in row:
        freq[val]=freq.get(val,0)+1

print("Elements ocurring only once: ")
for key in freq:
    if freq[key]==1:
        print(key,end=" ")

Elements ocurring only once: 
1 2 4 6 7 

In [10]:
"""Print all elements that are common across all rows of a 2D matrix."""
A=[[1,2,3,4],
   [3,4,5,2],
   [5,2,7,4]]

common=set(A[0])
for row in A[1:]:
    common=common.intersection(row)
print(common)

{2, 4}


In [11]:
"""Rotate a matrix by 90°, 180°, and 270° (clockwise or counterclockwise)"""
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("90° CW:\n", np.rot90(mat, -1))
print("180°:\n", np.rot90(mat, 2))
print("270° CW:\n", np.rot90(mat, 1))

90° CW:
 [[7 4 1]
 [8 5 2]
 [9 6 3]]
180°:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
270° CW:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]


In [12]:

""" Creta a menu driven python program to compute the addition , subtraction and 
multiplication of a given n*m matrix."""
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print("\nEnter elements of Matrix A:")
A = np.array([list(map(int, input().split())) for _ in range(rows)])

print("\nEnter elements of Matrix B:")
B = np.array([list(map(int, input().split())) for _ in range(rows)])

while True:
    print("\nMENU")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        print("\nAddition:")
        print(A + B)

    elif choice == 2:
        print("\nSubtraction:")
        print(A - B)

    elif choice == 3:
        if A.shape[1] != B.shape[0]:
            print("Multiplication not possible")
        else:
            print("\nMultiplication:")
            print(A @ B)   # or np.dot(A, B)

    elif choice == 4:
        print("Exiting...")
        break

    else:
        print("Invalid choice!")


Enter elements of Matrix A:

Enter elements of Matrix B:

MENU
1. Addition
2. Subtraction
3. Multiplication
4. Exit

Addition:
[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]

MENU
1. Addition
2. Subtraction
3. Multiplication
4. Exit


ValueError: invalid literal for int() with base 10: ''

In [ ]:
""" A smart campus energy monitoring system records the electricity consumption (in units) 
of four classrooms for 7 consecutive days. The collected data is stored in a structured 
format for analysis and decision
making.
As a data analyst, you are required to analyze the consumption patterns using NumPy.
Tasks:
a) Create a two-dimensional NumPy array to represent the electricity consumption data, where:
Each row represents a classroom.
Each column represents a day.
b) Compute and display:
The average electricity consumption of each classroom.
The average electricity consumption for each day
c) Identify:
The classroom with the highest total energy consumption over the week.
The day with the highest overall electricity consumption.
d) Compare the electricity usage of classrooms and comment on which classroom is the least energy-efficient
based on total consumption.
e) Sort the classrooms based on their weekly energy consumption and display the sorted result"""

A=np.random.randint(0,200,size=(4,7))
print(A)
print("Average electricity consumption for each classroom: ")
print(np.mean(A,axis=1))
print("Average electricity consumption for each day: ")
print(np.mean(A,axis=0))
print("Classroom with highest total energy consumption: ")
print("ClassRoom ",np.argmax(np.sum(A,axis=1))+1)
print("Day with highest total energy consumption")
print(np.argmax(np.sum(A,axis=0))+1)
print("The least energy efficient classroom: ")
print(np.argmax(np.sum(A,axis=1))+1)
print("Class sorted by consumption (low to high)")
for i in np.argsort(np.sum(A,axis=1)):
    print("Classroom",i+1,"-",np.sum(A,axis=1)[i])



[[103  97 167  33 102 164  32]
 [ 33 152  25  23   1 150   1]
 [ 85 199 139 120  74 120  25]
 [181   9  99  57 168  37 194]]
Average electricity consumption for each classroom: 
[ 99.71428571  55.         108.85714286 106.42857143]
Average electricity consumption for each day: 
[100.5  114.25 107.5   58.25  86.25 117.75  63.  ]
Classroom with highest total energy consumption: 
ClassRoom  3
Day with highest total energy consumption
6
The least energy efficient classroom: 
3
Class sorted by consumption (low to high)
Classroom 2 - 385
Classroom 1 - 698
Classroom 4 - 745
Classroom 3 - 762


In [14]:
import pandas as pd
mydata={'cars':['BMW','Mercedes','Porsche'],
        'year':[2019,2020,2021]}
df=pd.DataFrame(mydata)
print(df)

       cars  year
0       BMW  2019
1  Mercedes  2020
2   Porsche  2021


In [15]:
a=[1,3,8]
s=pd.Series(a)
print(s)

0    1
1    3
2    8
dtype: int64


In [16]:
d=pd.Series(a,index=['x','y','z'])
print(d)

x    1
y    3
z    8
dtype: int64


In [17]:
"""A cricket batsman’s runs scored during one week of practice matches are given below:
Runs:34,56,12,78,45,90,28
Days:MondaytoSunday
Create a Pandas Series using the runs scored,assigning the days of the week as index labels.
a. Calculate and print the average(mean) runs scored during the week.
b. Identify and print the maximum and minimum runs scored,along with the corresponding days on
which they were achieved."""

score=[34,56,12,78,45,90,28]
S=pd.Series(score,index=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print(S)
print("Average runs scored: ",S.mean())
minscore=S.min()
print("Least runs scored ",minscore,"on ",S.idxmin())
maxscore=S.max()
print("Least runs scored ",maxscore,"on ",S.idxmax())
       

Monday       34
Tuesday      56
Wednesday    12
Thursday     78
Friday       45
Saturday     90
Sunday       28
dtype: int64
Average runs scored:  49.0
Least runs scored  12 on  Wednesday
Least runs scored  90 on  Saturday


In [18]:
"""Write a Pandas program to add, subtract, multiple and divide two Pandas Series."""
A=[1,2,3,4,5]
B=[5,4,3,2,1]
sa=pd.Series(A)
sb=pd.Series(B)
print("Addition: ")
print(sa+sb)
print("Subtraction: ")
print(sa-sb)
print("Multiplication: ")
print(sa*sb)
print("Division: ")
print(sa/sb)

Addition: 
0    6
1    6
2    6
3    6
4    6
dtype: int64
Subtraction: 
0   -4
1   -2
2    0
3    2
4    4
dtype: int64
Multiplication: 
0    5
1    8
2    9
3    8
4    5
dtype: int64
Division: 
0    0.2
1    0.5
2    1.0
3    2.0
4    5.0
dtype: float64


In [ ]:
"""Write a Pandas program to sort a given Series"""
W=[3,8,5,9,1,0]
s=pd.Series(W)
print(s.sort_values())

5    0
4    1
0    3
2    5
1    8
3    9
dtype: int64


In [20]:
"""Write a Pandas program to get the items of a given series not present in another
given series."""
a=pd.Series([1,3,5,7,8])
b=pd.Series([2,1,5,4,7])
ans=a[~a.isin(b)]
print(ans)

1    3
4    8
dtype: int64


In [21]:
"""Write a Pandas program to calculate the frequency counts of each unique value of
a given series."""
G=[1,2,5,6,8,2,5,1,8,0]
s=pd.Series(G)
print(s.value_counts())


1    2
2    2
5    2
8    2
6    1
0    1
Name: count, dtype: int64


In [22]:
""" Write a Pandas program to select the rows where the number of attempts in the
examination is greater than 2"""
exam={'subject':['Math','Physics','Chem','Coding'],
      'Attempts':[2,1,4,1]}
df=pd.DataFrame(exam)
print(df)
print("Exams where more than 2 attempts: ")
print(df[df['Attempts']>2])

   subject  Attempts
0     Math         2
1  Physics         1
2     Chem         4
3   Coding         1
Exams where more than 2 attempts: 
  subject  Attempts
2    Chem         4


In [23]:
"""Write a Pandas program to replace all the NaN values with Zero's in a column of a
dataframe"""
data={'Hobby':[np.nan,'Partying','Trekking','Kayaking','snowboarding'],
      'Attempts':[2,np.nan,4,6,7]}
df=pd.DataFrame(data)
print(df)
df=df.fillna(0)
print(df)

          Hobby  Attempts
0           NaN       2.0
1      Partying       NaN
2      Trekking       4.0
3      Kayaking       6.0
4  snowboarding       7.0
          Hobby  Attempts
0             0       2.0
1      Partying       0.0
2      Trekking       4.0
3      Kayaking       6.0
4  snowboarding       7.0


In [37]:
""" Create a Series from a list of integers representing daily temperatures (in Celsius) over a week. 
Assign index labels as day of the week. 
a. Find and print the average (mean) temperature for the week. 
b. Identify and print the maximum and minimum temperatures and their respective days. 
c. Display the temperatures greater than a specific value. 
d. Convert all temperatures to Fahrenheit. 
e. Print the days had temperatures above the average. """
f=[43,46,48,44,48,46,39]
days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
s=pd.Series(f,index=days)
print(s)
mean_temp=s.mean(axis=0)
print("Mean temperature of the week: ")
print(mean_temp)
print("Max Temperature:",s.max(axis=0),"on",s.idxmax())
print("Min Temperature:",s.min(axis=0),"on",s.idxmin())
print("Temperatures above 45 degrees: ")
print(s[s>45])
ff=(s*(9/5.0))+32
print("Temperatures in F")
print(ff)
above_avg=s[s>mean_temp].index
print("Days when the temperature is above the average :",list(above_avg))



Monday       43
Tuesday      46
Wednesday    48
Thursday     44
Friday       48
Saturday     46
Sunday       39
dtype: int64
Mean temperature of the week: 
44.857142857142854
Max Temperature: 48 on Wednesday
Min Temperature: 39 on Sunday
Temperatures above 45 degrees: 
Tuesday      46
Wednesday    48
Friday       48
Saturday     46
dtype: int64
Temperatures in F
Monday       109.4
Tuesday      114.8
Wednesday    118.4
Thursday     111.2
Friday       118.4
Saturday     114.8
Sunday       102.2
dtype: float64
Days when the temperature is above the average : ['Tuesday', 'Wednesday', 'Friday', 'Saturday']
